import { ExternalLink } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { getSiteContent } from "@/lib/content-store";
import { listDonationSubmissions } from "@/lib/donation-store";
import { AdminHeader, AdminShell } from "@/components/admin/admin-shell";
import { reviewDonationAction, saveDonationAction, saveLedgerAction } from "@/app/admin/actions";

const input = "mt-2 w-full rounded-xl border border-line bg-white px-3 py-2.5 text-sm text-ink shadow-sm";
const money = (value: number) => `Rp ${value.toLocaleString("id-ID")}`;

export default async function DonationAdminPage() {
  await requireAdmin();
  const [{ donation, ledger }, submissions] = await Promise.all([getSiteContent(), listDonationSubmissions()]);
  const pendingCount = submissions.filter((item) => item.status === "pending").length;
  return <AdminShell><AdminHeader eyebrow="Donasi & transparansi" title="Kelola donasi masuk" description="Verifikasi bukti transfer sebelum nominalnya masuk ke total donasi publik." /><div className="max-w-6xl space-y-6 p-5 md:p-10">
    <form action={saveDonationAction} className="grid gap-5 rounded-2xl border border-line bg-white p-6 shadow-subtle md:grid-cols-2"><label className="text-sm font-semibold md:col-span-2">Judul<input className={input} name="heading" defaultValue={donation.heading} required /></label><label className="text-sm font-semibold md:col-span-2">Deskripsi<textarea className={input} name="description" defaultValue={donation.description} rows={3} required /></label><label className="text-sm font-semibold">Nama bank<input className={input} name="bankName" defaultValue={donation.bankName} required /></label><label className="text-sm font-semibold">Nomor rekening<input className={input} name="accountNumber" defaultValue={donation.accountNumber} required /></label><label className="text-sm font-semibold">Atas nama<input className={input} name="accountHolder" defaultValue={donation.accountHolder} required /></label><label className="text-sm font-semibold">Nomor WhatsApp konfirmasi<input className={input} name="confirmationWhatsapp" defaultValue={donation.confirmationWhatsapp} required /></label><label className="text-sm font-semibold md:col-span-2">Pesan konfirmasi<textarea className={input} name="confirmationMessage" defaultValue={donation.confirmationMessage} rows={3} required /></label><label className="text-sm font-semibold md:col-span-2">Judul transparansi<input className={input} name="transparencyHeading" defaultValue={donation.transparencyHeading} required /></label><button className="button-primary w-fit">Simpan Informasi Donasi</button></form>
    <section className="rounded-2xl border border-line bg-white p-6 shadow-subtle"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-heading text-xl font-bold">Bukti donasi masuk</h2><p className="mt-1 text-sm text-muted">{pendingCount ? `${pendingCount} donasi menunggu verifikasi.` : "Tidak ada donasi yang menunggu verifikasi."}</p></div><span className="rounded-full bg-orange/10 px-3 py-1 text-xs font-bold text-orange">{submissions.length} pengajuan</span></div>{submissions.length ? <div className="mt-6 space-y-4">{submissions.map((submission) => <article key={submission.id} className="rounded-2xl border border-line p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h3 className="font-heading text-lg font-bold text-ink">{submission.donorName}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${submission.status === "verified" ? "bg-green/10 text-green" : submission.status === "rejected" ? "bg-red-50 text-red-600" : "bg-orange/10 text-orange"}`}>{submission.status === "verified" ? "Terverifikasi" : submission.status === "rejected" ? "Ditolak" : "Menunggu"}</span></div><p className="mt-2 text-sm text-muted">{money(submission.amount)} · Transfer {submission.transferDate} · Dikirim {submission.createdAt.toLocaleDateString("id-ID")}</p>{submission.donorPhone && <p className="mt-1 text-sm text-muted">WhatsApp: {submission.donorPhone}</p>}{submission.note && <p className="mt-3 rounded-xl bg-[#f8fafc] p-3 text-sm text-muted">{submission.note}</p>}</div><a className="inline-flex items-center gap-2 text-sm font-bold text-orange hover:text-ink" href={submission.proofUrl} target="_blank" rel="noreferrer">Lihat bukti <ExternalLink className="h-4 w-4" /></a></div><form action={reviewDonationAction} className="mt-5 grid gap-3 border-t border-line pt-5 md:grid-cols-[1fr_auto_auto]"><input type="hidden" name="id" value={submission.id} /><input className={input.replace("mt-2", "")} name="adminNote" defaultValue={submission.adminNote} placeholder="Catatan admin (opsional)" maxLength={500} /><button className="rounded-full bg-green px-4 py-2 text-sm font-bold text-white hover:bg-green/90" name="status" value="verified">Verifikasi</button><button className="rounded-full border border-red-200 px-4 py-2 text-sm font-bold text-red-600 hover:bg-red-50" name="status" value="rejected">Tolak</button></form></article>)}</div> : <div className="mt-6 rounded-xl bg-[#f8fafc] p-8 text-center"><p className="font-semibold text-ink">Belum ada bukti donasi masuk.</p><p className="mt-1 text-sm text-muted">Pengajuan dari halaman donasi publik akan muncul di sini.</p></div>}</section>
    <section className="rounded-2xl border border-line bg-white p-6 shadow-subtle"><h2 className="font-heading text-xl font-bold">Ledger transparansi</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wider text-muted"><tr><th className="py-3">Tipe</th><th className="py-3">Keterangan</th><th className="py-3">Nominal</th><th className="py-3">Tanggal</th><th className="py-3">Publik</th></tr></thead><tbody className="divide-y divide-line">{ledger.map((entry) => <tr key={entry.id}><td className="py-4">{entry.type}</td><td className="py-4">{entry.description}</td><td className="py-4">{money(entry.amount)}</td><td className="py-4">{entry.date}</td><td className="py-4">{entry.public ? "Ya" : "Tidak"}</td></tr>)}</tbody></table></div><form action={saveLedgerAction} className="mt-8 grid gap-4 border-t border-line pt-6 md:grid-cols-5"><label className="text-sm font-semibold">Tipe<select className={input} name="type"><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></label><label className="text-sm font-semibold md:col-span-2">Keterangan<input className={input} name="description" required /></label><label className="text-sm font-semibold">Nominal<input className={input} name="amount" type="number" min={0} required /></label><label className="text-sm font-semibold">Tanggal<input className={input} name="date" type="date" required /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="public" /> Tampilkan ke publik</label><button className="button-primary w-fit">Tambah Catatan</button></form></section>
  </div></AdminShell>;
}
