import Link from "next/link";
import Image from "next/image";
import { BookOpen, CalendarDays, FileText, GalleryVerticalEnd, HeartHandshake, Home, LogOut, Settings, Users } from "lucide-react";
import type { ReactNode } from "react";
import { logoutAction } from "@/app/admin/actions";

const links = [["/admin", "Ringkasan", Home], ["/admin/home", "Beranda", FileText], ["/admin/pages", "Halaman", BookOpen], ["/admin/organization", "Pengurus", Users], ["/admin/schedule", "Jadwal", CalendarDays], ["/admin/news", "Berita", FileText], ["/admin/gallery", "Galeri", GalleryVerticalEnd], ["/admin/donation", "Donasi", HeartHandshake], ["/admin/settings", "Pengaturan", Settings]] as const;

export function AdminShell({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-[#f8fafc] text-ink"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-line bg-white p-5 lg:block"><Link href="/admin" className="flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-white p-1 shadow-sm"><Image src="/media/logo-payf.png" alt="Logo PAYF Al-Furqon Sanden" width={44} height={44} className="h-full w-full object-contain" /></span><span><b className="block font-heading text-lg">LKSA CMS</b><small className="text-xs text-muted">Panel Admin</small></span></Link><nav className="mt-10 grid gap-1">{links.map(([href, label, Icon]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-muted transition hover:bg-orange/10 hover:text-orange"><Icon className="h-4 w-4" />{label}</Link>)}</nav><form action={logoutAction} className="absolute bottom-5 left-5 right-5"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-muted hover:bg-red-50 hover:text-red-600"><LogOut className="h-4 w-4" />Keluar</button></form></aside><main className="lg:pl-64"><div className="border-b border-line bg-white px-5 py-4 lg:hidden"><div className="flex items-center justify-between"><Link href="/admin" className="font-heading text-lg font-bold">LKSA CMS</Link><form action={logoutAction}><button className="text-sm font-semibold text-muted">Keluar</button></form></div></div>{children}</main></div>; }
export function AdminHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="border-b border-line bg-white px-5 py-8 md:px-10"><div className="max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange">{eyebrow}</p><h1 className="mt-3 font-heading text-3xl font-bold text-ink md:text-4xl">{title}</h1><p className="mt-2 text-sm leading-6 text-muted">{description}</p></div></header>; }


